### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [EmmanuelCHH/Practica-1#1]
Muy bien, jóvenes. Gracias por el esfuerzo.

Les dejo algunas correcciones para que realicen:
- Agreguen un párrafo inventado sobre la historia de su empresa.
- Tienen un par de errores ortográficos, como escribir algún nombre con minúscula. Revisen eso.
- Cambien un poco el formato de sus nombres, para que resalte más.

Espero su respuesta, etiquétenme en este Issue para que me aparezca una notificación. Saludos.

**Comment by EmmanuelCHH** [comment]
@CarlosRubioTNM Listo, las correcciones fueron añadidas

**Comment by CarlosRubioTNM** [comment]
Ya lo revisé. Buen trabajo, jóvenes. Cierro el issue. 👍
